# Generated by Django 4.1.3 on 2023-02-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_post', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Post_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(unique=True, upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('type_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.type_of')),
                ('whose_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.user')),
            ],
        ),
    ]
