# Generated by Django 4.1.3 on 2023-02-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_about',
            name='photo',
            field=models.ImageField(unique=True, upload_to='images/'),
        ),
    ]
